Description: |
  This template launches an EC2 that enables SSH
Resources:
  MyEc2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:  ami-0ab4d1e9cf9a1215a 
      InstanceType: t2.micro
      KeyName: savas
      SecurityGroups:
        - SSH ve HTTP
      Tags:
        - Key: Name
          Value: savas-cf-stack-instance
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          #!/bin/bash
          yum update -y
          yum install -y httpd
          chmod -R 777 /var/www/html
          cd /var/www/html
          FOLDER="https://raw.githubusercontent.com/alexasiz/AWS-PythonProjects/main/python/projects/Project-101-kittens-carousel-static-website-ec2/static-web/"
          wget $FOLDER/index.html
          wget $FOLDER/cat0.jpg
          wget $FOLDER/cat1.jpg
          wget $FOLDER/cat2.jpg
          wget $FOLDER/cat3.png
          systemctl start httpd
          systemctl enable httpd